2019-04-14 11:52:21,226 ERROR 6132 nodejs.ClusterClientNoResponseError: client no response in 78812ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\study\egg\base-datebase-operate\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6132
hostname: DESKTOP-M4HQFS8

